'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="LGTCPN")>  _
Partial Public Class LINQ_CPNDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Insertsyslcnsnm(instance As syslcnsnm)
    End Sub
  Partial Private Sub Updatesyslcnsnm(instance As syslcnsnm)
    End Sub
  Partial Private Sub Deletesyslcnsnm(instance As syslcnsnm)
    End Sub
  Partial Private Sub Insertsyslctnm(instance As syslctnm)
    End Sub
  Partial Private Sub Updatesyslctnm(instance As syslctnm)
    End Sub
  Partial Private Sub Deletesyslctnm(instance As syslctnm)
    End Sub
  Partial Private Sub Insertsysprefix(instance As sysprefix)
    End Sub
  Partial Private Sub Updatesysprefix(instance As sysprefix)
    End Sub
  Partial Private Sub Deletesysprefix(instance As sysprefix)
    End Sub
  Partial Private Sub Insertsyslcnsid(instance As syslcnsid)
    End Sub
  Partial Private Sub Updatesyslcnsid(instance As syslcnsid)
    End Sub
  Partial Private Sub Deletesyslcnsid(instance As syslcnsid)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("LGTCPNConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property syslcnsnms() As System.Data.Linq.Table(Of syslcnsnm)
		Get
			Return Me.GetTable(Of syslcnsnm)
		End Get
	End Property
	
	Public ReadOnly Property syslctnms() As System.Data.Linq.Table(Of syslctnm)
		Get
			Return Me.GetTable(Of syslctnm)
		End Get
	End Property
	
	Public ReadOnly Property sysprefixes() As System.Data.Linq.Table(Of sysprefix)
		Get
			Return Me.GetTable(Of sysprefix)
		End Get
	End Property
	
	Public ReadOnly Property syslcnsids() As System.Data.Linq.Table(Of syslcnsid)
		Get
			Return Me.GetTable(Of syslcnsid)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.syslcnsnm")>  _
Partial Public Class syslcnsnm
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _identify As String
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _lcnscd As System.Nullable(Of Integer)
	
	Private _prefixcd As System.Nullable(Of Short)
	
	Private _prefixcd2 As System.Nullable(Of Short)
	
	Private _prefixnm As String
	
	Private _prefixnm2 As String
	
	Private _thanm As String
	
	Private _engnm As String
	
	Private _lctcd As System.Nullable(Of Integer)
	
	Private _thalnm As String
	
	Private _englnm As String
	
	Private _suffixcd As System.Nullable(Of Short)
	
	Private _lcnsst As System.Nullable(Of Short)
	
	Private _grplcnscd As System.Nullable(Of Short)
	
	Private _bsncd As System.Nullable(Of Integer)
	
	Private _lstfcd As System.Nullable(Of Integer)
	
	Private _lmdfdate As System.Nullable(Of Date)
	
	Private _lcnsidst As System.Nullable(Of Short)
	
	Private _validdate As System.Nullable(Of Date)
	
	Private _oldid As String
	
	Private _type As System.Nullable(Of Integer)
	
	Private _create_date As System.Nullable(Of Date)
	
	Private _update_date As System.Nullable(Of Date)
	
	Private _middle_name_th As String
	
	Private _middle_name_en As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnidentifyChanging(value As String)
    End Sub
    Partial Private Sub OnidentifyChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnlcnscdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnscdChanged()
    End Sub
    Partial Private Sub OnprefixcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnprefixcdChanged()
    End Sub
    Partial Private Sub Onprefixcd2Changing(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub Onprefixcd2Changed()
    End Sub
    Partial Private Sub OnprefixnmChanging(value As String)
    End Sub
    Partial Private Sub OnprefixnmChanged()
    End Sub
    Partial Private Sub Onprefixnm2Changing(value As String)
    End Sub
    Partial Private Sub Onprefixnm2Changed()
    End Sub
    Partial Private Sub OnthanmChanging(value As String)
    End Sub
    Partial Private Sub OnthanmChanged()
    End Sub
    Partial Private Sub OnengnmChanging(value As String)
    End Sub
    Partial Private Sub OnengnmChanged()
    End Sub
    Partial Private Sub OnlctcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctcdChanged()
    End Sub
    Partial Private Sub OnthalnmChanging(value As String)
    End Sub
    Partial Private Sub OnthalnmChanged()
    End Sub
    Partial Private Sub OnenglnmChanging(value As String)
    End Sub
    Partial Private Sub OnenglnmChanged()
    End Sub
    Partial Private Sub OnsuffixcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnsuffixcdChanged()
    End Sub
    Partial Private Sub OnlcnsstChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnlcnsstChanged()
    End Sub
    Partial Private Sub OngrplcnscdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OngrplcnscdChanged()
    End Sub
    Partial Private Sub OnbsncdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnbsncdChanged()
    End Sub
    Partial Private Sub OnlstfcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlstfcdChanged()
    End Sub
    Partial Private Sub OnlmdfdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnlmdfdateChanged()
    End Sub
    Partial Private Sub OnlcnsidstChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnlcnsidstChanged()
    End Sub
    Partial Private Sub OnvaliddateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnvaliddateChanged()
    End Sub
    Partial Private Sub OnoldidChanging(value As String)
    End Sub
    Partial Private Sub OnoldidChanged()
    End Sub
    Partial Private Sub OntypeChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OntypeChanged()
    End Sub
    Partial Private Sub Oncreate_dateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Oncreate_dateChanged()
    End Sub
    Partial Private Sub Onupdate_dateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Onupdate_dateChanged()
    End Sub
    Partial Private Sub Onmiddle_name_thChanging(value As String)
    End Sub
    Partial Private Sub Onmiddle_name_thChanged()
    End Sub
    Partial Private Sub Onmiddle_name_enChanging(value As String)
    End Sub
    Partial Private Sub Onmiddle_name_enChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_identify", DbType:="VarChar(100)")>  _
	Public Property identify() As String
		Get
			Return Me._identify
		End Get
		Set
			If (String.Equals(Me._identify, value) = false) Then
				Me.OnidentifyChanging(value)
				Me.SendPropertyChanging
				Me._identify = value
				Me.SendPropertyChanged("identify")
				Me.OnidentifyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnscd", DbType:="Int")>  _
	Public Property lcnscd() As System.Nullable(Of Integer)
		Get
			Return Me._lcnscd
		End Get
		Set
			If (Me._lcnscd.Equals(value) = false) Then
				Me.OnlcnscdChanging(value)
				Me.SendPropertyChanging
				Me._lcnscd = value
				Me.SendPropertyChanged("lcnscd")
				Me.OnlcnscdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prefixcd", DbType:="SmallInt")>  _
	Public Property prefixcd() As System.Nullable(Of Short)
		Get
			Return Me._prefixcd
		End Get
		Set
			If (Me._prefixcd.Equals(value) = false) Then
				Me.OnprefixcdChanging(value)
				Me.SendPropertyChanging
				Me._prefixcd = value
				Me.SendPropertyChanged("prefixcd")
				Me.OnprefixcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prefixcd2", DbType:="SmallInt")>  _
	Public Property prefixcd2() As System.Nullable(Of Short)
		Get
			Return Me._prefixcd2
		End Get
		Set
			If (Me._prefixcd2.Equals(value) = false) Then
				Me.Onprefixcd2Changing(value)
				Me.SendPropertyChanging
				Me._prefixcd2 = value
				Me.SendPropertyChanged("prefixcd2")
				Me.Onprefixcd2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prefixnm", DbType:="VarChar(MAX)")>  _
	Public Property prefixnm() As String
		Get
			Return Me._prefixnm
		End Get
		Set
			If (String.Equals(Me._prefixnm, value) = false) Then
				Me.OnprefixnmChanging(value)
				Me.SendPropertyChanging
				Me._prefixnm = value
				Me.SendPropertyChanged("prefixnm")
				Me.OnprefixnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prefixnm2", DbType:="VarChar(MAX)")>  _
	Public Property prefixnm2() As String
		Get
			Return Me._prefixnm2
		End Get
		Set
			If (String.Equals(Me._prefixnm2, value) = false) Then
				Me.Onprefixnm2Changing(value)
				Me.SendPropertyChanging
				Me._prefixnm2 = value
				Me.SendPropertyChanged("prefixnm2")
				Me.Onprefixnm2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanm", DbType:="VarChar(255)")>  _
	Public Property thanm() As String
		Get
			Return Me._thanm
		End Get
		Set
			If (String.Equals(Me._thanm, value) = false) Then
				Me.OnthanmChanging(value)
				Me.SendPropertyChanging
				Me._thanm = value
				Me.SendPropertyChanged("thanm")
				Me.OnthanmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engnm", DbType:="VarChar(100)")>  _
	Public Property engnm() As String
		Get
			Return Me._engnm
		End Get
		Set
			If (String.Equals(Me._engnm, value) = false) Then
				Me.OnengnmChanging(value)
				Me.SendPropertyChanging
				Me._engnm = value
				Me.SendPropertyChanged("engnm")
				Me.OnengnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctcd", DbType:="Int")>  _
	Public Property lctcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctcd
		End Get
		Set
			If (Me._lctcd.Equals(value) = false) Then
				Me.OnlctcdChanging(value)
				Me.SendPropertyChanging
				Me._lctcd = value
				Me.SendPropertyChanged("lctcd")
				Me.OnlctcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thalnm", DbType:="VarChar(100)")>  _
	Public Property thalnm() As String
		Get
			Return Me._thalnm
		End Get
		Set
			If (String.Equals(Me._thalnm, value) = false) Then
				Me.OnthalnmChanging(value)
				Me.SendPropertyChanging
				Me._thalnm = value
				Me.SendPropertyChanged("thalnm")
				Me.OnthalnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_englnm", DbType:="VarChar(100)")>  _
	Public Property englnm() As String
		Get
			Return Me._englnm
		End Get
		Set
			If (String.Equals(Me._englnm, value) = false) Then
				Me.OnenglnmChanging(value)
				Me.SendPropertyChanging
				Me._englnm = value
				Me.SendPropertyChanged("englnm")
				Me.OnenglnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_suffixcd", DbType:="SmallInt")>  _
	Public Property suffixcd() As System.Nullable(Of Short)
		Get
			Return Me._suffixcd
		End Get
		Set
			If (Me._suffixcd.Equals(value) = false) Then
				Me.OnsuffixcdChanging(value)
				Me.SendPropertyChanging
				Me._suffixcd = value
				Me.SendPropertyChanged("suffixcd")
				Me.OnsuffixcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsst", DbType:="SmallInt")>  _
	Public Property lcnsst() As System.Nullable(Of Short)
		Get
			Return Me._lcnsst
		End Get
		Set
			If (Me._lcnsst.Equals(value) = false) Then
				Me.OnlcnsstChanging(value)
				Me.SendPropertyChanging
				Me._lcnsst = value
				Me.SendPropertyChanged("lcnsst")
				Me.OnlcnsstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_grplcnscd", DbType:="SmallInt")>  _
	Public Property grplcnscd() As System.Nullable(Of Short)
		Get
			Return Me._grplcnscd
		End Get
		Set
			If (Me._grplcnscd.Equals(value) = false) Then
				Me.OngrplcnscdChanging(value)
				Me.SendPropertyChanging
				Me._grplcnscd = value
				Me.SendPropertyChanged("grplcnscd")
				Me.OngrplcnscdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_bsncd", DbType:="Int")>  _
	Public Property bsncd() As System.Nullable(Of Integer)
		Get
			Return Me._bsncd
		End Get
		Set
			If (Me._bsncd.Equals(value) = false) Then
				Me.OnbsncdChanging(value)
				Me.SendPropertyChanging
				Me._bsncd = value
				Me.SendPropertyChanged("bsncd")
				Me.OnbsncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lstfcd", DbType:="Int")>  _
	Public Property lstfcd() As System.Nullable(Of Integer)
		Get
			Return Me._lstfcd
		End Get
		Set
			If (Me._lstfcd.Equals(value) = false) Then
				Me.OnlstfcdChanging(value)
				Me.SendPropertyChanging
				Me._lstfcd = value
				Me.SendPropertyChanged("lstfcd")
				Me.OnlstfcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lmdfdate", DbType:="DateTime2")>  _
	Public Property lmdfdate() As System.Nullable(Of Date)
		Get
			Return Me._lmdfdate
		End Get
		Set
			If (Me._lmdfdate.Equals(value) = false) Then
				Me.OnlmdfdateChanging(value)
				Me.SendPropertyChanging
				Me._lmdfdate = value
				Me.SendPropertyChanged("lmdfdate")
				Me.OnlmdfdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsidst", DbType:="SmallInt")>  _
	Public Property lcnsidst() As System.Nullable(Of Short)
		Get
			Return Me._lcnsidst
		End Get
		Set
			If (Me._lcnsidst.Equals(value) = false) Then
				Me.OnlcnsidstChanging(value)
				Me.SendPropertyChanging
				Me._lcnsidst = value
				Me.SendPropertyChanged("lcnsidst")
				Me.OnlcnsidstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_validdate", DbType:="Date")>  _
	Public Property validdate() As System.Nullable(Of Date)
		Get
			Return Me._validdate
		End Get
		Set
			If (Me._validdate.Equals(value) = false) Then
				Me.OnvaliddateChanging(value)
				Me.SendPropertyChanging
				Me._validdate = value
				Me.SendPropertyChanged("validdate")
				Me.OnvaliddateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_oldid", DbType:="VarChar(60)")>  _
	Public Property oldid() As String
		Get
			Return Me._oldid
		End Get
		Set
			If (String.Equals(Me._oldid, value) = false) Then
				Me.OnoldidChanging(value)
				Me.SendPropertyChanging
				Me._oldid = value
				Me.SendPropertyChanged("oldid")
				Me.OnoldidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_type", DbType:="Int")>  _
	Public Property type() As System.Nullable(Of Integer)
		Get
			Return Me._type
		End Get
		Set
			If (Me._type.Equals(value) = false) Then
				Me.OntypeChanging(value)
				Me.SendPropertyChanging
				Me._type = value
				Me.SendPropertyChanged("type")
				Me.OntypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_create_date", DbType:="DateTime")>  _
	Public Property create_date() As System.Nullable(Of Date)
		Get
			Return Me._create_date
		End Get
		Set
			If (Me._create_date.Equals(value) = false) Then
				Me.Oncreate_dateChanging(value)
				Me.SendPropertyChanging
				Me._create_date = value
				Me.SendPropertyChanged("create_date")
				Me.Oncreate_dateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_update_date", DbType:="DateTime")>  _
	Public Property update_date() As System.Nullable(Of Date)
		Get
			Return Me._update_date
		End Get
		Set
			If (Me._update_date.Equals(value) = false) Then
				Me.Onupdate_dateChanging(value)
				Me.SendPropertyChanging
				Me._update_date = value
				Me.SendPropertyChanged("update_date")
				Me.Onupdate_dateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_middle_name_th", DbType:="NVarChar(MAX)")>  _
	Public Property middle_name_th() As String
		Get
			Return Me._middle_name_th
		End Get
		Set
			If (String.Equals(Me._middle_name_th, value) = false) Then
				Me.Onmiddle_name_thChanging(value)
				Me.SendPropertyChanging
				Me._middle_name_th = value
				Me.SendPropertyChanged("middle_name_th")
				Me.Onmiddle_name_thChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_middle_name_en", DbType:="NVarChar(MAX)")>  _
	Public Property middle_name_en() As String
		Get
			Return Me._middle_name_en
		End Get
		Set
			If (String.Equals(Me._middle_name_en, value) = false) Then
				Me.Onmiddle_name_enChanging(value)
				Me.SendPropertyChanging
				Me._middle_name_en = value
				Me.SendPropertyChanged("middle_name_en")
				Me.Onmiddle_name_enChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.syslctnm")>  _
Partial Public Class syslctnm
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _lcnsid As Integer
	
	Private _lctnmcd As Integer
	
	Private _prefixcd As System.Nullable(Of Short)
	
	Private _thanm As String
	
	Private _engnm As String
	
	Private _suffixcd As System.Nullable(Of Short)
	
	Private _lctst As Short
	
	Private _tpnost As System.Nullable(Of Short)
	
	Private _ltntpcd As System.Nullable(Of Integer)
	
	Private _hptno As String
	
	Private _lcttpcd As System.Nullable(Of Short)
	
	Private _lctcd As System.Nullable(Of Integer)
	
	Private _lctnmno As System.Nullable(Of Short)
	
	Private _lstfcd As System.Nullable(Of Integer)
	
	Private _dvcd As Short
	
	Private _lmdfdate As Date
	
	Private _chngwtcd As Short
	
	Private _grplctnmcd As System.Nullable(Of Short)
	
	Private _thanmold As String
	
	Private _prefixcdold As System.Nullable(Of Short)
	
	Private _IDA As Integer
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As Integer)
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnlctnmcdChanging(value As Integer)
    End Sub
    Partial Private Sub OnlctnmcdChanged()
    End Sub
    Partial Private Sub OnprefixcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnprefixcdChanged()
    End Sub
    Partial Private Sub OnthanmChanging(value As String)
    End Sub
    Partial Private Sub OnthanmChanged()
    End Sub
    Partial Private Sub OnengnmChanging(value As String)
    End Sub
    Partial Private Sub OnengnmChanged()
    End Sub
    Partial Private Sub OnsuffixcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnsuffixcdChanged()
    End Sub
    Partial Private Sub OnlctstChanging(value As Short)
    End Sub
    Partial Private Sub OnlctstChanged()
    End Sub
    Partial Private Sub OntpnostChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OntpnostChanged()
    End Sub
    Partial Private Sub OnltntpcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnltntpcdChanged()
    End Sub
    Partial Private Sub OnhptnoChanging(value As String)
    End Sub
    Partial Private Sub OnhptnoChanged()
    End Sub
    Partial Private Sub OnlcttpcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnlcttpcdChanged()
    End Sub
    Partial Private Sub OnlctcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctcdChanged()
    End Sub
    Partial Private Sub OnlctnmnoChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnlctnmnoChanged()
    End Sub
    Partial Private Sub OnlstfcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlstfcdChanged()
    End Sub
    Partial Private Sub OndvcdChanging(value As Short)
    End Sub
    Partial Private Sub OndvcdChanged()
    End Sub
    Partial Private Sub OnlmdfdateChanging(value As Date)
    End Sub
    Partial Private Sub OnlmdfdateChanged()
    End Sub
    Partial Private Sub OnchngwtcdChanging(value As Short)
    End Sub
    Partial Private Sub OnchngwtcdChanged()
    End Sub
    Partial Private Sub OngrplctnmcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OngrplctnmcdChanged()
    End Sub
    Partial Private Sub OnthanmoldChanging(value As String)
    End Sub
    Partial Private Sub OnthanmoldChanged()
    End Sub
    Partial Private Sub OnprefixcdoldChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnprefixcdoldChanged()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int NOT NULL")>  _
	Public Property lcnsid() As Integer
		Get
			Return Me._lcnsid
		End Get
		Set
			If ((Me._lcnsid = value)  _
						= false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmcd", DbType:="Int NOT NULL")>  _
	Public Property lctnmcd() As Integer
		Get
			Return Me._lctnmcd
		End Get
		Set
			If ((Me._lctnmcd = value)  _
						= false) Then
				Me.OnlctnmcdChanging(value)
				Me.SendPropertyChanging
				Me._lctnmcd = value
				Me.SendPropertyChanged("lctnmcd")
				Me.OnlctnmcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prefixcd", DbType:="SmallInt")>  _
	Public Property prefixcd() As System.Nullable(Of Short)
		Get
			Return Me._prefixcd
		End Get
		Set
			If (Me._prefixcd.Equals(value) = false) Then
				Me.OnprefixcdChanging(value)
				Me.SendPropertyChanging
				Me._prefixcd = value
				Me.SendPropertyChanged("prefixcd")
				Me.OnprefixcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanm", DbType:="VarChar(200) NOT NULL", CanBeNull:=false)>  _
	Public Property thanm() As String
		Get
			Return Me._thanm
		End Get
		Set
			If (String.Equals(Me._thanm, value) = false) Then
				Me.OnthanmChanging(value)
				Me.SendPropertyChanging
				Me._thanm = value
				Me.SendPropertyChanged("thanm")
				Me.OnthanmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engnm", DbType:="VarChar(200)")>  _
	Public Property engnm() As String
		Get
			Return Me._engnm
		End Get
		Set
			If (String.Equals(Me._engnm, value) = false) Then
				Me.OnengnmChanging(value)
				Me.SendPropertyChanging
				Me._engnm = value
				Me.SendPropertyChanged("engnm")
				Me.OnengnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_suffixcd", DbType:="SmallInt")>  _
	Public Property suffixcd() As System.Nullable(Of Short)
		Get
			Return Me._suffixcd
		End Get
		Set
			If (Me._suffixcd.Equals(value) = false) Then
				Me.OnsuffixcdChanging(value)
				Me.SendPropertyChanging
				Me._suffixcd = value
				Me.SendPropertyChanged("suffixcd")
				Me.OnsuffixcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctst", DbType:="SmallInt NOT NULL")>  _
	Public Property lctst() As Short
		Get
			Return Me._lctst
		End Get
		Set
			If ((Me._lctst = value)  _
						= false) Then
				Me.OnlctstChanging(value)
				Me.SendPropertyChanging
				Me._lctst = value
				Me.SendPropertyChanged("lctst")
				Me.OnlctstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tpnost", DbType:="SmallInt")>  _
	Public Property tpnost() As System.Nullable(Of Short)
		Get
			Return Me._tpnost
		End Get
		Set
			If (Me._tpnost.Equals(value) = false) Then
				Me.OntpnostChanging(value)
				Me.SendPropertyChanging
				Me._tpnost = value
				Me.SendPropertyChanged("tpnost")
				Me.OntpnostChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ltntpcd", DbType:="Int")>  _
	Public Property ltntpcd() As System.Nullable(Of Integer)
		Get
			Return Me._ltntpcd
		End Get
		Set
			If (Me._ltntpcd.Equals(value) = false) Then
				Me.OnltntpcdChanging(value)
				Me.SendPropertyChanging
				Me._ltntpcd = value
				Me.SendPropertyChanged("ltntpcd")
				Me.OnltntpcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hptno", DbType:="VarChar(30)")>  _
	Public Property hptno() As String
		Get
			Return Me._hptno
		End Get
		Set
			If (String.Equals(Me._hptno, value) = false) Then
				Me.OnhptnoChanging(value)
				Me.SendPropertyChanging
				Me._hptno = value
				Me.SendPropertyChanged("hptno")
				Me.OnhptnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcttpcd", DbType:="SmallInt")>  _
	Public Property lcttpcd() As System.Nullable(Of Short)
		Get
			Return Me._lcttpcd
		End Get
		Set
			If (Me._lcttpcd.Equals(value) = false) Then
				Me.OnlcttpcdChanging(value)
				Me.SendPropertyChanging
				Me._lcttpcd = value
				Me.SendPropertyChanged("lcttpcd")
				Me.OnlcttpcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctcd", DbType:="Int")>  _
	Public Property lctcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctcd
		End Get
		Set
			If (Me._lctcd.Equals(value) = false) Then
				Me.OnlctcdChanging(value)
				Me.SendPropertyChanging
				Me._lctcd = value
				Me.SendPropertyChanged("lctcd")
				Me.OnlctcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmno", DbType:="SmallInt")>  _
	Public Property lctnmno() As System.Nullable(Of Short)
		Get
			Return Me._lctnmno
		End Get
		Set
			If (Me._lctnmno.Equals(value) = false) Then
				Me.OnlctnmnoChanging(value)
				Me.SendPropertyChanging
				Me._lctnmno = value
				Me.SendPropertyChanged("lctnmno")
				Me.OnlctnmnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lstfcd", DbType:="Int")>  _
	Public Property lstfcd() As System.Nullable(Of Integer)
		Get
			Return Me._lstfcd
		End Get
		Set
			If (Me._lstfcd.Equals(value) = false) Then
				Me.OnlstfcdChanging(value)
				Me.SendPropertyChanging
				Me._lstfcd = value
				Me.SendPropertyChanged("lstfcd")
				Me.OnlstfcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dvcd", DbType:="SmallInt NOT NULL")>  _
	Public Property dvcd() As Short
		Get
			Return Me._dvcd
		End Get
		Set
			If ((Me._dvcd = value)  _
						= false) Then
				Me.OndvcdChanging(value)
				Me.SendPropertyChanging
				Me._dvcd = value
				Me.SendPropertyChanged("dvcd")
				Me.OndvcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lmdfdate", DbType:="DateTime2 NOT NULL")>  _
	Public Property lmdfdate() As Date
		Get
			Return Me._lmdfdate
		End Get
		Set
			If ((Me._lmdfdate = value)  _
						= false) Then
				Me.OnlmdfdateChanging(value)
				Me.SendPropertyChanging
				Me._lmdfdate = value
				Me.SendPropertyChanged("lmdfdate")
				Me.OnlmdfdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_chngwtcd", DbType:="SmallInt NOT NULL")>  _
	Public Property chngwtcd() As Short
		Get
			Return Me._chngwtcd
		End Get
		Set
			If ((Me._chngwtcd = value)  _
						= false) Then
				Me.OnchngwtcdChanging(value)
				Me.SendPropertyChanging
				Me._chngwtcd = value
				Me.SendPropertyChanged("chngwtcd")
				Me.OnchngwtcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_grplctnmcd", DbType:="SmallInt")>  _
	Public Property grplctnmcd() As System.Nullable(Of Short)
		Get
			Return Me._grplctnmcd
		End Get
		Set
			If (Me._grplctnmcd.Equals(value) = false) Then
				Me.OngrplctnmcdChanging(value)
				Me.SendPropertyChanging
				Me._grplctnmcd = value
				Me.SendPropertyChanged("grplctnmcd")
				Me.OngrplctnmcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanmold", DbType:="VarChar(200)")>  _
	Public Property thanmold() As String
		Get
			Return Me._thanmold
		End Get
		Set
			If (String.Equals(Me._thanmold, value) = false) Then
				Me.OnthanmoldChanging(value)
				Me.SendPropertyChanging
				Me._thanmold = value
				Me.SendPropertyChanged("thanmold")
				Me.OnthanmoldChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prefixcdold", DbType:="SmallInt")>  _
	Public Property prefixcdold() As System.Nullable(Of Short)
		Get
			Return Me._prefixcdold
		End Get
		Set
			If (Me._prefixcdold.Equals(value) = false) Then
				Me.OnprefixcdoldChanging(value)
				Me.SendPropertyChanging
				Me._prefixcdold = value
				Me.SendPropertyChanged("prefixcdold")
				Me.OnprefixcdoldChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.sysprefix")>  _
Partial Public Class sysprefix
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _prefixcd As System.Nullable(Of Short)
	
	Private _thanm As String
	
	Private _engnm As String
	
	Private _thaabbr As String
	
	Private _engabbr As String
	
	Private _prefixst As System.Nullable(Of Short)
	
	Private _cscprfxcd As System.Nullable(Of Short)
	
	Private _group_prefix As System.Nullable(Of Integer)
	
	Private _bitenble As System.Nullable(Of Integer)
	
	Private _ida As Integer
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnprefixcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnprefixcdChanged()
    End Sub
    Partial Private Sub OnthanmChanging(value As String)
    End Sub
    Partial Private Sub OnthanmChanged()
    End Sub
    Partial Private Sub OnengnmChanging(value As String)
    End Sub
    Partial Private Sub OnengnmChanged()
    End Sub
    Partial Private Sub OnthaabbrChanging(value As String)
    End Sub
    Partial Private Sub OnthaabbrChanged()
    End Sub
    Partial Private Sub OnengabbrChanging(value As String)
    End Sub
    Partial Private Sub OnengabbrChanged()
    End Sub
    Partial Private Sub OnprefixstChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnprefixstChanged()
    End Sub
    Partial Private Sub OncscprfxcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OncscprfxcdChanged()
    End Sub
    Partial Private Sub Ongroup_prefixChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Ongroup_prefixChanged()
    End Sub
    Partial Private Sub OnbitenbleChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnbitenbleChanged()
    End Sub
    Partial Private Sub OnidaChanging(value As Integer)
    End Sub
    Partial Private Sub OnidaChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prefixcd", DbType:="SmallInt")>  _
	Public Property prefixcd() As System.Nullable(Of Short)
		Get
			Return Me._prefixcd
		End Get
		Set
			If (Me._prefixcd.Equals(value) = false) Then
				Me.OnprefixcdChanging(value)
				Me.SendPropertyChanging
				Me._prefixcd = value
				Me.SendPropertyChanged("prefixcd")
				Me.OnprefixcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanm", DbType:="VarChar(50)")>  _
	Public Property thanm() As String
		Get
			Return Me._thanm
		End Get
		Set
			If (String.Equals(Me._thanm, value) = false) Then
				Me.OnthanmChanging(value)
				Me.SendPropertyChanging
				Me._thanm = value
				Me.SendPropertyChanged("thanm")
				Me.OnthanmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engnm", DbType:="VarChar(50)")>  _
	Public Property engnm() As String
		Get
			Return Me._engnm
		End Get
		Set
			If (String.Equals(Me._engnm, value) = false) Then
				Me.OnengnmChanging(value)
				Me.SendPropertyChanging
				Me._engnm = value
				Me.SendPropertyChanged("engnm")
				Me.OnengnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thaabbr", DbType:="VarChar(35)")>  _
	Public Property thaabbr() As String
		Get
			Return Me._thaabbr
		End Get
		Set
			If (String.Equals(Me._thaabbr, value) = false) Then
				Me.OnthaabbrChanging(value)
				Me.SendPropertyChanging
				Me._thaabbr = value
				Me.SendPropertyChanged("thaabbr")
				Me.OnthaabbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engabbr", DbType:="VarChar(35)")>  _
	Public Property engabbr() As String
		Get
			Return Me._engabbr
		End Get
		Set
			If (String.Equals(Me._engabbr, value) = false) Then
				Me.OnengabbrChanging(value)
				Me.SendPropertyChanging
				Me._engabbr = value
				Me.SendPropertyChanged("engabbr")
				Me.OnengabbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prefixst", DbType:="SmallInt")>  _
	Public Property prefixst() As System.Nullable(Of Short)
		Get
			Return Me._prefixst
		End Get
		Set
			If (Me._prefixst.Equals(value) = false) Then
				Me.OnprefixstChanging(value)
				Me.SendPropertyChanging
				Me._prefixst = value
				Me.SendPropertyChanged("prefixst")
				Me.OnprefixstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cscprfxcd", DbType:="SmallInt")>  _
	Public Property cscprfxcd() As System.Nullable(Of Short)
		Get
			Return Me._cscprfxcd
		End Get
		Set
			If (Me._cscprfxcd.Equals(value) = false) Then
				Me.OncscprfxcdChanging(value)
				Me.SendPropertyChanging
				Me._cscprfxcd = value
				Me.SendPropertyChanged("cscprfxcd")
				Me.OncscprfxcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_group_prefix", DbType:="Int")>  _
	Public Property group_prefix() As System.Nullable(Of Integer)
		Get
			Return Me._group_prefix
		End Get
		Set
			If (Me._group_prefix.Equals(value) = false) Then
				Me.Ongroup_prefixChanging(value)
				Me.SendPropertyChanging
				Me._group_prefix = value
				Me.SendPropertyChanged("group_prefix")
				Me.Ongroup_prefixChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_bitenble", DbType:="Int")>  _
	Public Property bitenble() As System.Nullable(Of Integer)
		Get
			Return Me._bitenble
		End Get
		Set
			If (Me._bitenble.Equals(value) = false) Then
				Me.OnbitenbleChanging(value)
				Me.SendPropertyChanging
				Me._bitenble = value
				Me.SendPropertyChanged("bitenble")
				Me.OnbitenbleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ida", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ida() As Integer
		Get
			Return Me._ida
		End Get
		Set
			If ((Me._ida = value)  _
						= false) Then
				Me.OnidaChanging(value)
				Me.SendPropertyChanging
				Me._ida = value
				Me.SendPropertyChanged("ida")
				Me.OnidaChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.syslcnsid")>  _
Partial Public Class syslcnsid
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _identify As String
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _crtlct As System.Nullable(Of Short)
	
	Private _birthdate As System.Nullable(Of Date)
	
	Private _chngwtcd As System.Nullable(Of Short)
	
	Private _ntcd As System.Nullable(Of Short)
	
	Private _taxno As String
	
	Private _trdregno As String
	
	Private _ctzno As String
	
	Private _remark As String
	
	Private _idst As System.Nullable(Of Short)
	
	Private _phrno As String
	
	Private _stfcd As System.Nullable(Of Integer)
	
	Private _nmprnst As System.Nullable(Of Short)
	
	Private _cncdate As System.Nullable(Of Date)
	
	Private _lstfcd As System.Nullable(Of Integer)
	
	Private _lcnsidst As System.Nullable(Of Short)
	
	Private _scridst As System.Nullable(Of Short)
	
	Private _lmdfdate As System.Nullable(Of Date)
	
	Private _url As String
	
	Private _cncremark As String
	
	Private _email As String
	
	Private _otaxno As String
	
	Private _type As System.Nullable(Of Integer)
	
	Private _email_sro As String
	
	Private _email_contract_real As String
	
	Private _ID_main As String
	
	Private _status As System.Nullable(Of Integer)
	
	Private _person_status_ID As System.Nullable(Of Integer)
	
	Private _person_status As String
	
	Private _sex As String
	
	Private _standard_description As String
	
	Private _register_capital As String
	
	Private _gmail As String
	
	Private _nation As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnidentifyChanging(value As String)
    End Sub
    Partial Private Sub OnidentifyChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OncrtlctChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OncrtlctChanged()
    End Sub
    Partial Private Sub OnbirthdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnbirthdateChanged()
    End Sub
    Partial Private Sub OnchngwtcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnchngwtcdChanged()
    End Sub
    Partial Private Sub OnntcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnntcdChanged()
    End Sub
    Partial Private Sub OntaxnoChanging(value As String)
    End Sub
    Partial Private Sub OntaxnoChanged()
    End Sub
    Partial Private Sub OntrdregnoChanging(value As String)
    End Sub
    Partial Private Sub OntrdregnoChanged()
    End Sub
    Partial Private Sub OnctznoChanging(value As String)
    End Sub
    Partial Private Sub OnctznoChanged()
    End Sub
    Partial Private Sub OnremarkChanging(value As String)
    End Sub
    Partial Private Sub OnremarkChanged()
    End Sub
    Partial Private Sub OnidstChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnidstChanged()
    End Sub
    Partial Private Sub OnphrnoChanging(value As String)
    End Sub
    Partial Private Sub OnphrnoChanged()
    End Sub
    Partial Private Sub OnstfcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnstfcdChanged()
    End Sub
    Partial Private Sub OnnmprnstChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnnmprnstChanged()
    End Sub
    Partial Private Sub OncncdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OncncdateChanged()
    End Sub
    Partial Private Sub OnlstfcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlstfcdChanged()
    End Sub
    Partial Private Sub OnlcnsidstChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnlcnsidstChanged()
    End Sub
    Partial Private Sub OnscridstChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnscridstChanged()
    End Sub
    Partial Private Sub OnlmdfdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnlmdfdateChanged()
    End Sub
    Partial Private Sub OnurlChanging(value As String)
    End Sub
    Partial Private Sub OnurlChanged()
    End Sub
    Partial Private Sub OncncremarkChanging(value As String)
    End Sub
    Partial Private Sub OncncremarkChanged()
    End Sub
    Partial Private Sub OnemailChanging(value As String)
    End Sub
    Partial Private Sub OnemailChanged()
    End Sub
    Partial Private Sub OnotaxnoChanging(value As String)
    End Sub
    Partial Private Sub OnotaxnoChanged()
    End Sub
    Partial Private Sub OntypeChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OntypeChanged()
    End Sub
    Partial Private Sub Onemail_sroChanging(value As String)
    End Sub
    Partial Private Sub Onemail_sroChanged()
    End Sub
    Partial Private Sub Onemail_contract_realChanging(value As String)
    End Sub
    Partial Private Sub Onemail_contract_realChanged()
    End Sub
    Partial Private Sub OnID_mainChanging(value As String)
    End Sub
    Partial Private Sub OnID_mainChanged()
    End Sub
    Partial Private Sub OnstatusChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnstatusChanged()
    End Sub
    Partial Private Sub Onperson_status_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onperson_status_IDChanged()
    End Sub
    Partial Private Sub Onperson_statusChanging(value As String)
    End Sub
    Partial Private Sub Onperson_statusChanged()
    End Sub
    Partial Private Sub OnsexChanging(value As String)
    End Sub
    Partial Private Sub OnsexChanged()
    End Sub
    Partial Private Sub Onstandard_descriptionChanging(value As String)
    End Sub
    Partial Private Sub Onstandard_descriptionChanged()
    End Sub
    Partial Private Sub Onregister_capitalChanging(value As String)
    End Sub
    Partial Private Sub Onregister_capitalChanged()
    End Sub
    Partial Private Sub OngmailChanging(value As String)
    End Sub
    Partial Private Sub OngmailChanged()
    End Sub
    Partial Private Sub OnnationChanging(value As String)
    End Sub
    Partial Private Sub OnnationChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_identify", DbType:="VarChar(100)")>  _
	Public Property identify() As String
		Get
			Return Me._identify
		End Get
		Set
			If (String.Equals(Me._identify, value) = false) Then
				Me.OnidentifyChanging(value)
				Me.SendPropertyChanging
				Me._identify = value
				Me.SendPropertyChanged("identify")
				Me.OnidentifyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_crtlct", DbType:="SmallInt")>  _
	Public Property crtlct() As System.Nullable(Of Short)
		Get
			Return Me._crtlct
		End Get
		Set
			If (Me._crtlct.Equals(value) = false) Then
				Me.OncrtlctChanging(value)
				Me.SendPropertyChanging
				Me._crtlct = value
				Me.SendPropertyChanged("crtlct")
				Me.OncrtlctChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_birthdate", DbType:="Date")>  _
	Public Property birthdate() As System.Nullable(Of Date)
		Get
			Return Me._birthdate
		End Get
		Set
			If (Me._birthdate.Equals(value) = false) Then
				Me.OnbirthdateChanging(value)
				Me.SendPropertyChanging
				Me._birthdate = value
				Me.SendPropertyChanged("birthdate")
				Me.OnbirthdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_chngwtcd", DbType:="SmallInt")>  _
	Public Property chngwtcd() As System.Nullable(Of Short)
		Get
			Return Me._chngwtcd
		End Get
		Set
			If (Me._chngwtcd.Equals(value) = false) Then
				Me.OnchngwtcdChanging(value)
				Me.SendPropertyChanging
				Me._chngwtcd = value
				Me.SendPropertyChanged("chngwtcd")
				Me.OnchngwtcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ntcd", DbType:="SmallInt")>  _
	Public Property ntcd() As System.Nullable(Of Short)
		Get
			Return Me._ntcd
		End Get
		Set
			If (Me._ntcd.Equals(value) = false) Then
				Me.OnntcdChanging(value)
				Me.SendPropertyChanging
				Me._ntcd = value
				Me.SendPropertyChanged("ntcd")
				Me.OnntcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_taxno", DbType:="VarChar(100)")>  _
	Public Property taxno() As String
		Get
			Return Me._taxno
		End Get
		Set
			If (String.Equals(Me._taxno, value) = false) Then
				Me.OntaxnoChanging(value)
				Me.SendPropertyChanging
				Me._taxno = value
				Me.SendPropertyChanged("taxno")
				Me.OntaxnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_trdregno", DbType:="VarChar(100)")>  _
	Public Property trdregno() As String
		Get
			Return Me._trdregno
		End Get
		Set
			If (String.Equals(Me._trdregno, value) = false) Then
				Me.OntrdregnoChanging(value)
				Me.SendPropertyChanging
				Me._trdregno = value
				Me.SendPropertyChanged("trdregno")
				Me.OntrdregnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ctzno", DbType:="VarChar(100)")>  _
	Public Property ctzno() As String
		Get
			Return Me._ctzno
		End Get
		Set
			If (String.Equals(Me._ctzno, value) = false) Then
				Me.OnctznoChanging(value)
				Me.SendPropertyChanging
				Me._ctzno = value
				Me.SendPropertyChanged("ctzno")
				Me.OnctznoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_remark", DbType:="VarChar(40)")>  _
	Public Property remark() As String
		Get
			Return Me._remark
		End Get
		Set
			If (String.Equals(Me._remark, value) = false) Then
				Me.OnremarkChanging(value)
				Me.SendPropertyChanging
				Me._remark = value
				Me.SendPropertyChanged("remark")
				Me.OnremarkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idst", DbType:="SmallInt")>  _
	Public Property idst() As System.Nullable(Of Short)
		Get
			Return Me._idst
		End Get
		Set
			If (Me._idst.Equals(value) = false) Then
				Me.OnidstChanging(value)
				Me.SendPropertyChanging
				Me._idst = value
				Me.SendPropertyChanged("idst")
				Me.OnidstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_phrno", DbType:="VarChar(20)")>  _
	Public Property phrno() As String
		Get
			Return Me._phrno
		End Get
		Set
			If (String.Equals(Me._phrno, value) = false) Then
				Me.OnphrnoChanging(value)
				Me.SendPropertyChanging
				Me._phrno = value
				Me.SendPropertyChanged("phrno")
				Me.OnphrnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stfcd", DbType:="Int")>  _
	Public Property stfcd() As System.Nullable(Of Integer)
		Get
			Return Me._stfcd
		End Get
		Set
			If (Me._stfcd.Equals(value) = false) Then
				Me.OnstfcdChanging(value)
				Me.SendPropertyChanging
				Me._stfcd = value
				Me.SendPropertyChanged("stfcd")
				Me.OnstfcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nmprnst", DbType:="SmallInt")>  _
	Public Property nmprnst() As System.Nullable(Of Short)
		Get
			Return Me._nmprnst
		End Get
		Set
			If (Me._nmprnst.Equals(value) = false) Then
				Me.OnnmprnstChanging(value)
				Me.SendPropertyChanging
				Me._nmprnst = value
				Me.SendPropertyChanged("nmprnst")
				Me.OnnmprnstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cncdate", DbType:="Date")>  _
	Public Property cncdate() As System.Nullable(Of Date)
		Get
			Return Me._cncdate
		End Get
		Set
			If (Me._cncdate.Equals(value) = false) Then
				Me.OncncdateChanging(value)
				Me.SendPropertyChanging
				Me._cncdate = value
				Me.SendPropertyChanged("cncdate")
				Me.OncncdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lstfcd", DbType:="Int")>  _
	Public Property lstfcd() As System.Nullable(Of Integer)
		Get
			Return Me._lstfcd
		End Get
		Set
			If (Me._lstfcd.Equals(value) = false) Then
				Me.OnlstfcdChanging(value)
				Me.SendPropertyChanging
				Me._lstfcd = value
				Me.SendPropertyChanged("lstfcd")
				Me.OnlstfcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsidst", DbType:="SmallInt")>  _
	Public Property lcnsidst() As System.Nullable(Of Short)
		Get
			Return Me._lcnsidst
		End Get
		Set
			If (Me._lcnsidst.Equals(value) = false) Then
				Me.OnlcnsidstChanging(value)
				Me.SendPropertyChanging
				Me._lcnsidst = value
				Me.SendPropertyChanged("lcnsidst")
				Me.OnlcnsidstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_scridst", DbType:="SmallInt")>  _
	Public Property scridst() As System.Nullable(Of Short)
		Get
			Return Me._scridst
		End Get
		Set
			If (Me._scridst.Equals(value) = false) Then
				Me.OnscridstChanging(value)
				Me.SendPropertyChanging
				Me._scridst = value
				Me.SendPropertyChanged("scridst")
				Me.OnscridstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lmdfdate", DbType:="DateTime2")>  _
	Public Property lmdfdate() As System.Nullable(Of Date)
		Get
			Return Me._lmdfdate
		End Get
		Set
			If (Me._lmdfdate.Equals(value) = false) Then
				Me.OnlmdfdateChanging(value)
				Me.SendPropertyChanging
				Me._lmdfdate = value
				Me.SendPropertyChanged("lmdfdate")
				Me.OnlmdfdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_url", DbType:="VarChar(250)")>  _
	Public Property url() As String
		Get
			Return Me._url
		End Get
		Set
			If (String.Equals(Me._url, value) = false) Then
				Me.OnurlChanging(value)
				Me.SendPropertyChanging
				Me._url = value
				Me.SendPropertyChanged("url")
				Me.OnurlChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cncremark", DbType:="VarChar(250)")>  _
	Public Property cncremark() As String
		Get
			Return Me._cncremark
		End Get
		Set
			If (String.Equals(Me._cncremark, value) = false) Then
				Me.OncncremarkChanging(value)
				Me.SendPropertyChanging
				Me._cncremark = value
				Me.SendPropertyChanged("cncremark")
				Me.OncncremarkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_email", DbType:="VarChar(100)")>  _
	Public Property email() As String
		Get
			Return Me._email
		End Get
		Set
			If (String.Equals(Me._email, value) = false) Then
				Me.OnemailChanging(value)
				Me.SendPropertyChanging
				Me._email = value
				Me.SendPropertyChanged("email")
				Me.OnemailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_otaxno", DbType:="VarChar(20)")>  _
	Public Property otaxno() As String
		Get
			Return Me._otaxno
		End Get
		Set
			If (String.Equals(Me._otaxno, value) = false) Then
				Me.OnotaxnoChanging(value)
				Me.SendPropertyChanging
				Me._otaxno = value
				Me.SendPropertyChanged("otaxno")
				Me.OnotaxnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_type", DbType:="Int")>  _
	Public Property type() As System.Nullable(Of Integer)
		Get
			Return Me._type
		End Get
		Set
			If (Me._type.Equals(value) = false) Then
				Me.OntypeChanging(value)
				Me.SendPropertyChanging
				Me._type = value
				Me.SendPropertyChanged("type")
				Me.OntypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_email_sro", DbType:="VarChar(MAX)")>  _
	Public Property email_sro() As String
		Get
			Return Me._email_sro
		End Get
		Set
			If (String.Equals(Me._email_sro, value) = false) Then
				Me.Onemail_sroChanging(value)
				Me.SendPropertyChanging
				Me._email_sro = value
				Me.SendPropertyChanged("email_sro")
				Me.Onemail_sroChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_email_contract_real", DbType:="VarChar(MAX)")>  _
	Public Property email_contract_real() As String
		Get
			Return Me._email_contract_real
		End Get
		Set
			If (String.Equals(Me._email_contract_real, value) = false) Then
				Me.Onemail_contract_realChanging(value)
				Me.SendPropertyChanging
				Me._email_contract_real = value
				Me.SendPropertyChanged("email_contract_real")
				Me.Onemail_contract_realChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID_main", DbType:="VarChar(MAX)")>  _
	Public Property ID_main() As String
		Get
			Return Me._ID_main
		End Get
		Set
			If (String.Equals(Me._ID_main, value) = false) Then
				Me.OnID_mainChanging(value)
				Me.SendPropertyChanging
				Me._ID_main = value
				Me.SendPropertyChanged("ID_main")
				Me.OnID_mainChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_status", DbType:="Int")>  _
	Public Property status() As System.Nullable(Of Integer)
		Get
			Return Me._status
		End Get
		Set
			If (Me._status.Equals(value) = false) Then
				Me.OnstatusChanging(value)
				Me.SendPropertyChanging
				Me._status = value
				Me.SendPropertyChanged("status")
				Me.OnstatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_person_status_ID", DbType:="Int")>  _
	Public Property person_status_ID() As System.Nullable(Of Integer)
		Get
			Return Me._person_status_ID
		End Get
		Set
			If (Me._person_status_ID.Equals(value) = false) Then
				Me.Onperson_status_IDChanging(value)
				Me.SendPropertyChanging
				Me._person_status_ID = value
				Me.SendPropertyChanged("person_status_ID")
				Me.Onperson_status_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_person_status", DbType:="VarChar(MAX)")>  _
	Public Property person_status() As String
		Get
			Return Me._person_status
		End Get
		Set
			If (String.Equals(Me._person_status, value) = false) Then
				Me.Onperson_statusChanging(value)
				Me.SendPropertyChanging
				Me._person_status = value
				Me.SendPropertyChanged("person_status")
				Me.Onperson_statusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sex", DbType:="VarChar(MAX)")>  _
	Public Property sex() As String
		Get
			Return Me._sex
		End Get
		Set
			If (String.Equals(Me._sex, value) = false) Then
				Me.OnsexChanging(value)
				Me.SendPropertyChanging
				Me._sex = value
				Me.SendPropertyChanged("sex")
				Me.OnsexChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_standard_description", DbType:="VarChar(MAX)")>  _
	Public Property standard_description() As String
		Get
			Return Me._standard_description
		End Get
		Set
			If (String.Equals(Me._standard_description, value) = false) Then
				Me.Onstandard_descriptionChanging(value)
				Me.SendPropertyChanging
				Me._standard_description = value
				Me.SendPropertyChanged("standard_description")
				Me.Onstandard_descriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_register_capital", DbType:="VarChar(MAX)")>  _
	Public Property register_capital() As String
		Get
			Return Me._register_capital
		End Get
		Set
			If (String.Equals(Me._register_capital, value) = false) Then
				Me.Onregister_capitalChanging(value)
				Me.SendPropertyChanging
				Me._register_capital = value
				Me.SendPropertyChanged("register_capital")
				Me.Onregister_capitalChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_gmail", DbType:="VarChar(MAX)")>  _
	Public Property gmail() As String
		Get
			Return Me._gmail
		End Get
		Set
			If (String.Equals(Me._gmail, value) = false) Then
				Me.OngmailChanging(value)
				Me.SendPropertyChanging
				Me._gmail = value
				Me.SendPropertyChanged("gmail")
				Me.OngmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nation", DbType:="NVarChar(MAX)")>  _
	Public Property nation() As String
		Get
			Return Me._nation
		End Get
		Set
			If (String.Equals(Me._nation, value) = false) Then
				Me.OnnationChanging(value)
				Me.SendPropertyChanging
				Me._nation = value
				Me.SendPropertyChanged("nation")
				Me.OnnationChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
